'use client';
import { useEffect,useRef,useState } from 'react';
import { Button } from '../../components/ui/Button';
import { Card } from '../../components/ui/Card';
import { StatusChip } from '../../components/ui/StatusChip';
import { deriveCycleVaultKeyAsync,openCycleVaultV1 } from '../../crypto/cyclevault';
import { CycleVaultWebService } from '../../crypto/cyclevault-service';
import { useI18n } from '../../i18n/I18nProvider';
import { DexieVaultPersistence } from '../../vault/db';
import { HealthVaultRepository } from '../../vault/health-repository';
import { LOCAL_ONLY_DATA_LOSS_WARNING,VaultService } from '../../vault/vault-service';
import { continuePrivately } from '../onboarding/private-onboarding';
const CYCLEVAULT_MEMORY_KIB=19*1024;
function downloadCycleVault(container:string){const blob=new Blob([container],{type:'application/octet-stream'}),url=URL.createObjectURL(blob),anchor=document.createElement('a');anchor.href=url;anchor.download=`sreadya-${new Date().toISOString().replaceAll(':','-')}.cyclevault`;anchor.click();URL.revokeObjectURL(url);}
function base64ToBytes(value:string){const binary=atob(value),bytes=new Uint8Array(binary.length);for(let i=0;i<binary.length;i+=1)bytes[i]=binary.charCodeAt(i);return bytes;}
function bytesToHex(bytes:Uint8Array){return Array.from(bytes,value=>value.toString(16).padStart(2,'0')).join('');}
export function CycleVaultWorkspace(){
 const {t}=useI18n(),serviceRef=useRef<CycleVaultWebService|null>(null),vaultRef=useRef<VaultService|null>(null);const[ready,setReady]=useState(false),[status,setStatus]=useState(()=>t('core.vault.opening')),[error,setError]=useState(''),[exportPassphrase,setExportPassphrase]=useState(''),[exportConfirmation,setExportConfirmation]=useState(''),[exporting,setExporting]=useState(false),[restoreFileName,setRestoreFileName]=useState(''),[restoreContainer,setRestoreContainer]=useState(''),[restorePassphrase,setRestorePassphrase]=useState(''),[restoreAcknowledged,setRestoreAcknowledged]=useState(false),[restoring,setRestoring]=useState(false),[testPassphrase,setTestPassphrase]=useState(''),[testSalt,setTestSalt]=useState(''),[testContainer,setTestContainer]=useState(''),[testKey,setTestKey]=useState(''),[testLatency,setTestLatency]=useState(''),[testPayload,setTestPayload]=useState('');const testHarness=process.env.NEXT_PUBLIC_SREADYA_CYCLEVAULT_TEST_HARNESS==='1';
 useEffect(()=>{let cancelled=false;const vault=new VaultService(new DexieVaultPersistence());vaultRef.current=vault;void(async()=>{await continuePrivately(vault);if(cancelled)return;serviceRef.current=new CycleVaultWebService(new HealthVaultRepository(vault));setStatus(t('core.vault.ready'));setReady(true);})().catch(()=>{if(cancelled)return;setStatus(t('core.vault.unavailable'));setError(t('core.error.openVault'));setReady(true);});return()=>{cancelled=true;serviceRef.current=null;vault.lock();vaultRef.current=null;};},[t]);
 async function exportBackup(){const service=serviceRef.current;if(!service)return;setError('');if(exportPassphrase.length<12){setError(t('vault.error.passphraseLength'));return;}if(exportPassphrase!==exportConfirmation){setError(t('vault.error.passphraseMatch'));return;}setExporting(true);try{const container=await service.exportContainer(exportPassphrase);downloadCycleVault(container);setExportPassphrase('');setExportConfirmation('');setStatus(t('vault.status.downloaded'));}catch {setError(t('vault.error.export'));}finally{setExporting(false);}}
 async function selectRestoreFile(file:File|null){setError('');setRestoreAcknowledged(false);setRestoreContainer('');setRestoreFileName(file?.name??'');if(!file)return;try{setRestoreContainer(await file.text());setStatus(t('vault.status.selected'));}catch{setError(t('vault.error.read'));}}
 async function restoreBackup(){const service=serviceRef.current;if(!service||!restoreContainer||!restoreAcknowledged)return;setError('');setRestoring(true);try{const restored=await service.restoreContainer(restoreContainer,restorePassphrase);setStatus(t('vault.status.restored',{periods:restored.periods,observations:restored.observations}));setRestoreContainer('');setRestoreFileName('');setRestorePassphrase('');setRestoreAcknowledged(false);}catch{setError(t('vault.error.restore'));}finally{setRestoring(false);}}
 async function benchmarkTestKdf(){setTestKey('');setTestLatency('');try{const startedAt=performance.now(),key=await deriveCycleVaultKeyAsync(testPassphrase,base64ToBytes(testSalt)),elapsedMs=performance.now()-startedAt;try{setTestKey(bytesToHex(key));setTestLatency(String(elapsedMs));}finally{key.fill(0);}}catch{setTestKey('CycleVault KDF failed');setTestLatency('NaN');}}
 async function decryptTestVector(){setTestPayload('');try{setTestPayload(JSON.stringify(await openCycleVaultV1(testContainer,testPassphrase)));}catch{setTestPayload('CycleVault decrypt failed');}}
 return <section className="account-free-core" data-testid="cyclevault-workspace" aria-busy={!ready}><div className="account-free-core__status"><StatusChip tone={error?'danger':ready?'success':'info'}>{status}</StatusChip><span className="workspace-note">{t('vault.status')}</span></div><p className="vault-local-panel__warning"><strong>{t('vault.localWarningTitle')}</strong> {t('vault.localWarningBody',{},LOCAL_ONLY_DATA_LOSS_WARNING)}</p><p className="workspace-note">{t('vault.summary')}</p>{error?<p className="core-error" role="alert">{error}</p>:null}
 {ready?<div className="workspace-grid"><Card eyebrow={t('vault.backupEyebrow')} title={t('vault.backupTitle')}><p>{t('vault.backupBody')}</p><div className="core-date-form"><label><span>{t('vault.passphrase')}</span><input aria-label={t('vault.exportPassphraseAria')} type="password" autoComplete="new-password" value={exportPassphrase} onChange={e=>setExportPassphrase(e.target.value)}/></label><label><span>{t('vault.confirm')}</span><input aria-label={t('vault.confirmPassphraseAria')} type="password" autoComplete="new-password" value={exportConfirmation} onChange={e=>setExportConfirmation(e.target.value)}/></label></div><Button disabled={exporting} onClick={()=>{void exportBackup();}}>{exporting?t('vault.encrypting'):t('vault.download')}</Button></Card>
 <Card eyebrow={t('vault.recoveryEyebrow')} title={t('vault.recoveryTitle')}><p>{t('vault.recoveryBody')}</p><label><span>{t('vault.file')}</span><input aria-label={t('vault.file')} type="file" accept=".cyclevault,application/octet-stream" onChange={e=>{void selectRestoreFile(e.currentTarget.files?.[0]??null);}}/></label>{restoreFileName?<p className="workspace-note" data-testid="cyclevault-selected-file">{t('vault.selected',{file:restoreFileName})}</p>:null}<label><span>{t('vault.passphrase')}</span><input aria-label={t('vault.restorePassphraseAria')} type="password" autoComplete="current-password" value={restorePassphrase} onChange={e=>setRestorePassphrase(e.target.value)}/></label><label className="core-check-row"><input aria-label={t('vault.ackAria')} type="checkbox" checked={restoreAcknowledged} onChange={e=>setRestoreAcknowledged(e.target.checked)}/><span>{t('vault.ack')}</span></label><Button variant="secondary" disabled={restoring||!restoreContainer||!restorePassphrase||!restoreAcknowledged} onClick={()=>{void restoreBackup();}}>{restoring?t('vault.restoring'):t('vault.replace')}</Button><p className="workspace-note">{t('vault.restoreBoundary')}</p></Card></div>:null}
 {/* i18n-test-harness-start */}
 {testHarness?<div className="vault-test-harness" data-testid="cyclevault-test-harness"><p><strong>CycleVault interoperability verification only.</strong> Argon2id memory: {CYCLEVAULT_MEMORY_KIB} KiB.</p><label htmlFor="cyclevault-test-passphrase">CycleVault test passphrase</label><input id="cyclevault-test-passphrase" type="password" autoComplete="off" value={testPassphrase} onChange={e=>setTestPassphrase(e.target.value)}/><label htmlFor="cyclevault-test-salt">CycleVault test salt</label><input id="cyclevault-test-salt" value={testSalt} onChange={e=>setTestSalt(e.target.value)}/><Button onClick={()=>{void benchmarkTestKdf();}}>Benchmark CycleVault KDF</Button><output data-testid="cyclevault-test-key">{testKey}</output><output data-testid="cyclevault-test-latency">{testLatency}</output><label htmlFor="cyclevault-test-container">CycleVault test container</label><textarea id="cyclevault-test-container" value={testContainer} onChange={e=>setTestContainer(e.target.value)}/><Button variant="secondary" onClick={()=>{void decryptTestVector();}}>Decrypt CycleVault vector</Button><output data-testid="cyclevault-test-payload">{testPayload}</output></div>:null}
 {/* i18n-test-harness-end */}
 </section>;
}
