// Generated by tool/i18n_pipeline.py. Do not hand-edit.
export const GENERATED_TRANSLATION_AVAILABILITY = {
  "en": {
    "coverage": "source",
    "englishName": "English",
    "locale": "en",
    "method": "source",
    "provider": "sreadya",
    "reviewStatus": "source-authoritative"
  }
} as const;
export type GeneratedTranslationLanguage = keyof typeof GENERATED_TRANSLATION_AVAILABILITY;
