// Generated by tool/i18n_pipeline.py. Do not hand-edit.
export const GENERATED_TRANSLATION_AVAILABILITY = {
  "ar": {
    "coverage": "partial",
    "method": "machine",
    "reviewStatus": "machine-unreviewed"
  },
  "en": {
    "coverage": "source",
    "method": "source",
    "reviewStatus": "source-authoritative"
  },
  "fi": {
    "coverage": "partial",
    "method": "machine",
    "reviewStatus": "machine-unreviewed"
  },
  "hi": {
    "coverage": "partial",
    "method": "machine",
    "reviewStatus": "machine-unreviewed"
  },
  "ta": {
    "coverage": "partial",
    "method": "machine",
    "reviewStatus": "machine-unreviewed"
  }
} as const;
export type GeneratedTranslationLanguage = keyof typeof GENERATED_TRANSLATION_AVAILABILITY;
