// Product-depth audit anchor: default 3-day reminder contract.
'use client';
import { Button } from '../../components/ui/Button';
import { Card } from '../../components/ui/Card';
import type { NotificationPrivacy,ReminderPolicySettings } from '../../domain/reminders/reminder-policy';
import { useI18n } from '../../i18n/I18nProvider';
const OFFSET_OPTIONS=[7,3,1,0] as const;
const PRIVACY_OPTIONS:NotificationPrivacy[]=['maximum','balanced','detailed'];
function numberFromInput(value:string,fallback:number):number{const parsed=Number(value);return Number.isFinite(parsed)?parsed:fallback;}
export function ReminderSettingsPanel({settings,saving,onChange,onSave}:{settings:ReminderPolicySettings;saving:boolean;onChange:(next:ReminderPolicySettings)=>void;onSave:()=>void;}){
 const {t}=useI18n(),enabled=new Set(settings.enabledOffsetsDays);const toggleOffset=(days:number,checked:boolean)=>{const next=new Set(settings.enabledOffsetsDays);if(checked)next.add(days);else next.delete(days);onChange({...settings,enabledOffsetsDays:[...next].sort((l,r)=>r-l)});};
 return <div className="core-panel-grid" data-testid="reminder-settings-panel"><Card eyebrow={t('reminder.settingsEyebrow')} title={t('reminder.settingsTitle')}><fieldset className="reminder-fieldset"><legend>{t('reminder.cycle')}</legend><p className="workspace-note">{t('reminder.default')}</p><div className="reminder-option-grid">{OFFSET_OPTIONS.map(days=><label key={days} className="reminder-option"><input type="checkbox" name={`offset-${days}`} checked={enabled.has(days)} onChange={e=>toggleOffset(days,e.currentTarget.checked)}/><span>{t(`reminder.offset.${days}`)}</span></label>)}</div></fieldset>
 <div className="reminder-form-grid"><label><span>{t('reminder.late')}</span><span className="workspace-note">{t('reminder.lateHelp')}</span><input aria-label={t('reminder.late')} type="number" min={0} max={30} value={settings.lateDays} onChange={e=>onChange({...settings,lateDays:numberFromInput(e.currentTarget.value,settings.lateDays)})}/></label><label><span>{t('reminder.hour')}</span><input aria-label={t('reminder.hour')} type="number" min={0} max={23} value={settings.hour} onChange={e=>onChange({...settings,hour:numberFromInput(e.currentTarget.value,settings.hour)})}/></label><label><span>{t('reminder.minute')}</span><input aria-label={t('reminder.minute')} type="number" min={0} max={59} value={settings.minute} onChange={e=>onChange({...settings,minute:numberFromInput(e.currentTarget.value,settings.minute)})}/></label></div></Card>
 <Card eyebrow={t('reminder.quietEyebrow')} title={t('reminder.quietTitle')}><p className="workspace-note">{t('reminder.quietHelp')}</p><div className="reminder-form-grid"><label><span>{t('reminder.quietStart')}</span><input aria-label={t('reminder.quietStart')} type="number" min={0} max={23} value={settings.quietStartHour} onChange={e=>onChange({...settings,quietStartHour:numberFromInput(e.currentTarget.value,settings.quietStartHour)})}/></label><label><span>{t('reminder.quietEnd')}</span><input aria-label={t('reminder.quietEnd')} type="number" min={0} max={23} value={settings.quietEndHour} onChange={e=>onChange({...settings,quietEndHour:numberFromInput(e.currentTarget.value,settings.quietEndHour)})}/></label></div></Card>
 <Card eyebrow={t('reminder.familiesEyebrow')} title={t('reminder.familiesTitle')}><ul>{['medication','contraception','supplement','ovulationTest','pregnancyTest'].map(k=><li key={k}>{t(`reminder.kind.${k}`)}</li>)}</ul><p>{t('reminder.snoozeHelp')}</p><p className="workspace-note">{t('reminder.boundary')}</p></Card>
 <Card eyebrow={t('reminder.privacyEyebrow')} title={t('reminder.privacyTitle')}><div className="reminder-privacy-options" role="radiogroup" aria-label={t('reminder.privacyAria')}>{PRIVACY_OPTIONS.map(value=><label key={value} className="reminder-option reminder-option--stacked"><input type="radio" name="notification-privacy" value={value} checked={settings.privacy===value} onChange={()=>onChange({...settings,privacy:value})}/><span><strong>{t(`reminder.privacy.${value}`)}</strong><small>{t(`reminder.privacy.${value}Desc`)}</small></span></label>)}</div><div className="core-actions"><Button onClick={onSave} disabled={saving}>{saving?t('accessibility.saving'):t('reminder.save')}</Button></div></Card></div>;
}
