'use client';
import { useEffect,useRef,useState } from 'react';
import { Button } from '../../components/ui/Button';
import { Card } from '../../components/ui/Card';
import { StatusChip } from '../../components/ui/StatusChip';
import { formatLocaleDate } from '../../i18n/locale';
import { useI18n } from '../../i18n/I18nProvider';
import { DexieVaultPersistence } from '../../vault/db';
import { HealthVaultRepository } from '../../vault/health-repository';
import { VaultService } from '../../vault/vault-service';
import { ObservationActions } from '../cycle/observation-actions';
import { PersonalReminderRepository } from '../reminders/personal-reminder-repository';
import { PeriodActions } from '../cycle/period-actions';
import { continuePrivately } from '../onboarding/private-onboarding';
import { predictFromRepository } from '../predictions/prediction-service';
import { parseLocalIntent,type ParsedCommand } from './local-intent-parser';
function utcMidnight(dateKey:string):string{return `${dateKey}T00:00:00.000Z`;}
export function AssistantWorkspace(){
 const {t,locale}=useI18n(),repositoryRef=useRef<HealthVaultRepository|null>(null),reminderRepositoryRef=useRef<PersonalReminderRepository|null>(null);const[text,setText]=useState(''),[command,setCommand]=useState<ParsedCommand|null>(null),[answer,setAnswer]=useState<string|null>(null),[ready,setReady]=useState(false),[status,setStatus]=useState(()=>t('core.vault.opening')),[error,setError]=useState('');
 const displayDate=(dateKey:string)=>formatLocaleDate(`${dateKey}T00:00:00.000Z`,locale,'UTC');
 useEffect(()=>{let cancelled=false;const vault=new VaultService(new DexieVaultPersistence());void(async()=>{await continuePrivately(vault);if(cancelled)return;repositoryRef.current=new HealthVaultRepository(vault);reminderRepositoryRef.current=new PersonalReminderRepository(vault);setStatus(t('core.vault.ready'));setReady(true);})().catch(()=>{if(cancelled)return;setStatus(t('core.vault.unavailable'));setError(t('assistant.error.open'));setReady(true);});return()=>{cancelled=true;repositoryRef.current=null;reminderRepositoryRef.current=null;vault.lock();};},[t]);
 const interpret=async()=>{const repository=repositoryRef.current;if(!repository||!text.trim())return;setError('');const parsed=parseLocalIntent(text,new Date());setCommand(parsed);setAnswer(null);if(parsed.intent==='nextPeriodQuery'){const p=await predictFromRepository(repository,new Date().toISOString());setAnswer(p===null?t('assistant.needHistory'):t('assistant.prediction',{date:displayDate(p.mostLikelyDate),start:displayDate(p.windowStart),end:displayDate(p.windowEnd),confidence:p.confidence}));}else if(parsed.intent==='historyQuery'){const recent=(await repository.listPeriods()).slice(-6).reverse();setAnswer(recent.length===0?t('assistant.noHistory'):recent.map(p=>displayDate(p.start.slice(0,10))).join(' · '));}else if(parsed.intent==='searchHistory'){const q=(parsed.value??'').toLowerCase(),matches=(await repository.listObservations()).filter(item=>item.kind.toLowerCase().includes(q)||item.label?.toLowerCase().includes(q)||item.note?.toLowerCase().includes(q)).slice(-10).reverse();setAnswer(matches.length===0?t('assistant.noMatch',{query:parsed.value??''}):matches.map(item=>`${displayDate(item.occurredAt.slice(0,10))}: ${item.label??t(`observation.kind.${item.kind}`,{},item.kind)}`).join(' · '));}else if(parsed.intent==='addReminder')setAnswer(t('assistant.reminderParsed'));else if(parsed.intent==='unknown')setAnswer(t('assistant.unknown'));};
 const confirm=async()=>{const repository=repositoryRef.current;if(!repository||!command)return;setError('');if(command.intent==='unknown'){setError(t('assistant.error.unknown'));return;}try{if(command.intent==='periodStarted'&&command.date)await new PeriodActions(repository).startPeriod(utcMidnight(command.date));else if(command.intent==='periodEnded'&&command.date){const open=(await repository.listPeriods()).filter(p=>p.end==null).at(-1);if(!open){setError(t('assistant.error.noOngoing'));return;}await new PeriodActions(repository).endPeriod(open.id,utcMidnight(command.date));}else if((command.intent==='logFlow'||command.intent==='logSymptom')&&command.date)await new ObservationActions(repository).logObservation({kind:command.observationKind??'custom',occurredAt:utcMidnight(command.date),...(command.severity?{severity:command.severity}:{}),...(command.flowLevel?{flowLevel:command.flowLevel}:{}),...(command.note?{note:command.note}:{})});else if(command.intent==='addReminder'){const reminders=reminderRepositoryRef.current;if(!reminders){setError(t('assistant.error.reminderStore'));return;}if(command.reminderHour===undefined){setError(t('assistant.error.reminderTime'));return;}await reminders.save({id:crypto.randomUUID(),kind:command.reminderKind??'medication',label:command.label??t('assistant.defaultReminder'),hour:command.reminderHour,minute:command.reminderMinute??0,enabled:true,snoozeMinutes:10,timeZone:Intl.DateTimeFormat().resolvedOptions().timeZone||'UTC',createdAt:new Date().toISOString()});}else return;setStatus(t('core.saved'));setText('');setCommand(null);setAnswer(null);}catch{setError(t('assistant.error.save'));}};
 return <section className="account-free-core" data-testid="assistant-workspace" aria-busy={!ready}><div className="account-free-core__status"><StatusChip tone={error?'danger':ready?'success':'info'}>{status}</StatusChip><span className="workspace-note">{t('assistant.status')}</span></div>{error?<p className="core-error" role="alert">{error}</p>:null}{ready?<div className="workspace-grid">
 <Card eyebrow={t('assistant.eyebrow')} title={t('assistant.title')}><p>{t('assistant.examples')}</p><label><span>{t('assistant.command')}</span><textarea aria-label={t('assistant.command')} rows={4} value={text} onChange={e=>{setText(e.target.value);setCommand(null);setAnswer(null);}}/></label><Button disabled={!text.trim()} onClick={()=>{void interpret();}}>{t('assistant.understand')}</Button><p className="workspace-note">{t('assistant.voiceBoundary')}</p></Card>
 <Card eyebrow={t('assistant.interpretEyebrow')} title={t('assistant.interpretTitle')}>{!command?<p>{t('assistant.none')}</p>:<><p>{t('assistant.intent',{intent:t(`assistant.intentValue.${command.intent}`)})}</p>{command.date?<p>{t('assistant.date',{date:displayDate(command.date)})}</p>:null}{command.label?<p>{t('assistant.detail',{detail:command.label})}</p>:null}{command.reminderHour!==undefined?<p>{t('assistant.reminderTime',{time:`${String(command.reminderHour).padStart(2,'0')}:${String(command.reminderMinute??0).padStart(2,'0')}`})}</p>:null}{answer?<p data-testid="assistant-answer">{answer}</p>:null}{command.requiresConfirmation&&command.intent!=='unknown'?<Button onClick={()=>{void confirm();}}>{t('assistant.confirm')}</Button>:null}</>}</Card>
 </div>:null}</section>;
}
