'use client';
import type { ReactNode } from 'react';
import { useEffect,useRef,useState } from 'react';
import { Button } from '../components/ui/Button';
import { useI18n } from '../i18n/I18nProvider';
import { getAutoLockMinutes,isPinConfigured,verifyPin } from './app-lock';
const CHANGE_EVENT='sreadya-app-lock-changed';
export function WebAppLockGate({children}:{children:ReactNode}){
 const {t}=useI18n();const[hydrated,setHydrated]=useState(false),[configured,setConfigured]=useState(true),[unlocked,setUnlocked]=useState(false),[pin,setPin]=useState(''),[error,setError]=useState(''),[failures,setFailures]=useState(0),[blockedUntil,setBlockedUntil]=useState(0);const lastActivity=useRef(Date.now());
 useEffect(()=>{const synchronize=()=>{const nextConfigured=isPinConfigured(window.localStorage);setConfigured(nextConfigured);setUnlocked(!nextConfigured);setPin('');setError('');lastActivity.current=Date.now();setHydrated(true);};synchronize();window.addEventListener(CHANGE_EVENT,synchronize);return()=>window.removeEventListener(CHANGE_EVENT,synchronize);},[]);
 useEffect(()=>{if(!hydrated||!configured||!unlocked)return;const touch=()=>{lastActivity.current=Date.now();},automaticLock=()=>{const minutes=getAutoLockMinutes(window.localStorage);if(Date.now()-lastActivity.current>=minutes*60_000){setUnlocked(false);setPin('');setError('');}},visibility=()=>{if(document.visibilityState==='hidden'){setUnlocked(false);setPin('');setError('');}};window.addEventListener('pointerdown',touch,{passive:true});window.addEventListener('keydown',touch);window.addEventListener('focus',touch);document.addEventListener('visibilitychange',visibility);const timer=window.setInterval(automaticLock,15_000);return()=>{window.removeEventListener('pointerdown',touch);window.removeEventListener('keydown',touch);window.removeEventListener('focus',touch);document.removeEventListener('visibilitychange',visibility);window.clearInterval(timer);};},[configured,hydrated,unlocked]);
 const unlock=async()=>{if(Date.now()<blockedUntil){setError(t('appLock.tooMany'));return;}const valid=await verifyPin(window.localStorage,pin);if(valid){setUnlocked(true);setPin('');setError('');setFailures(0);lastActivity.current=Date.now();return;}const nextFailures=failures+1;setFailures(nextFailures);setPin('');if(nextFailures>=5){setBlockedUntil(Date.now()+30_000);setFailures(0);setError(t('appLock.paused'));}else setError(t('appLock.incorrect'));};
 if(!hydrated)return <main className="app-lock-screen" aria-busy="true"><p>{t('appLock.opening')}</p></main>;
 if(configured&&!unlocked)return <main className="app-lock-screen"><section className="app-lock-card" aria-labelledby="app-lock-title"><span className="workspace-topbar__mark" aria-hidden="true">S</span><p className="public-eyebrow">{t('appLock.locked')}</p><h1 id="app-lock-title">{t('appLock.unlockTitle')}</h1><p>{t('appLock.unlockBody')}</p><form onSubmit={e=>{e.preventDefault();void unlock();}}><label><span>{t('appLock.pin')}</span><input aria-label="Sreadya PIN" type="password" inputMode="numeric" pattern="[0-9]*" autoComplete="off" value={pin} onChange={e=>setPin(e.target.value)}/></label><Button type="submit" disabled={pin.length<4}>{t('appLock.unlock')}</Button></form>{error?<p className="core-error" role="alert">{error}</p>:null}<p className="workspace-note">{t('appLock.autoNote')}</p></section></main>;
 return <>{children}</>;
}
export const SREADYA_APP_LOCK_CHANGE_EVENT=CHANGE_EVENT;
