'use client';
import { useEffect,useRef,useState } from 'react';
import { QRCodeSVG } from 'qrcode.react';
import { Button } from '../../components/ui/Button';
import { Card } from '../../components/ui/Card';
import { StatusChip } from '../../components/ui/StatusChip';
import { formatLocaleDate } from '../../i18n/locale';
import { useI18n } from '../../i18n/I18nProvider';
import { DexieVaultPersistence } from '../../vault/db';
import { HealthVaultRepository } from '../../vault/health-repository';
import { VaultService } from '../../vault/vault-service';
import { continuePrivately } from '../onboarding/private-onboarding';
import { predictFromRepository } from '../predictions/prediction-service';
import { PartnerGrantRepository } from './partner-grant-repository';
import { PARTNER_SHARE_CATEGORIES,buildPartnerSharePackage,createPartnerGrant,revokePartnerGrant,type PartnerGrant,type PartnerShareCategory,type PartnerSharePackage } from './partner-sharing';
type Runtime={vault:VaultService;health:HealthVaultRepository;grants:PartnerGrantRepository};
export function SharingWorkspace(){
 const {t,locale}=useI18n();const runtimeRef=useRef<Runtime|null>(null);const[categories,setCategories]=useState<PartnerShareCategory[]>(['prediction']);const[cyclePhase,setCyclePhase]=useState(''),[selectedReminder,setSelectedReminder]=useState(''),[selectedWellness,setSelectedWellness]=useState('');const[grant,setGrant]=useState<PartnerGrant|null>(null),[sharePackage,setSharePackage]=useState<PartnerSharePackage|null>(null),[ready,setReady]=useState(false),[status,setStatus]=useState(()=>t('core.vault.opening')),[error,setError]=useState('');
 const label=(c:PartnerShareCategory)=>t(`sharing.category.${c}`);const displayDate=(d:string)=>formatLocaleDate(`${d}T00:00:00.000Z`,locale,'UTC');
 useEffect(()=>{let cancelled=false;const vault=new VaultService(new DexieVaultPersistence());void(async()=>{await continuePrivately(vault);if(cancelled)return;runtimeRef.current={vault,health:new HealthVaultRepository(vault),grants:new PartnerGrantRepository(vault)};setStatus(t('core.vault.ready'));setReady(true);})().catch(()=>{if(cancelled)return;setStatus(t('core.vault.unavailable'));setError(t('sharing.error.open'));setReady(true);});return()=>{cancelled=true;runtimeRef.current=null;vault.lock();};},[t]);
 const invalidate=()=>{setGrant(null);setSharePackage(null);};const toggle=(c:PartnerShareCategory,checked:boolean)=>{setCategories(cur=>checked?[...cur,c]:cur.filter(x=>x!==c));invalidate();};
 const prepare=async()=>{const r=runtimeRef.current;if(!r)return;setError('');try{if(!categories.length)throw new Error(t('sharing.error.category'));if(categories.includes('cyclePhase')&&!cyclePhase.trim())throw new Error(t('sharing.error.cycle'));if(categories.includes('selectedReminder')&&!selectedReminder.trim())throw new Error(t('sharing.error.reminder'));if(categories.includes('selectedWellness')&&!selectedWellness.trim())throw new Error(t('sharing.error.wellness'));let predictionWindow:string|undefined;if(categories.includes('prediction')){const p=await predictFromRepository(r.health,new Date().toISOString());if(!p)throw new Error(t('sharing.error.prediction'));predictionWindow=`${displayDate(p.windowStart)} – ${displayDate(p.windowEnd)}`;}const nextGrant=createPartnerGrant({id:crypto.randomUUID(),categories,createdAt:new Date().toISOString()});await r.grants.save(nextGrant);const nextPackage=buildPartnerSharePackage({grant:nextGrant,...(predictionWindow?{predictionWindow}:{}),...(cyclePhase.trim()?{cyclePhase:cyclePhase.trim()}:{}),...(selectedReminder.trim()?{selectedReminder:selectedReminder.trim()}:{}),...(selectedWellness.trim()?{selectedWellness:selectedWellness.trim()}:{})});setGrant(nextGrant);setSharePackage(nextPackage);setStatus(t('sharing.status.saved'));}catch(cause){setGrant(null);setSharePackage(null);setError(cause instanceof Error?cause.message:t('sharing.error.prepare'));}};
 const share=async()=>{if(!sharePackage)return;setError('');try{if(typeof navigator.share==='function'){await navigator.share({title:t('sharing.shareTitle'),text:sharePackage.shareText});setStatus(t('sharing.status.sheet'));}else if(navigator.clipboard?.writeText){await navigator.clipboard.writeText(sharePackage.shareText);setStatus(t('sharing.status.copied'));}else throw new Error(t('sharing.error.mechanism'));}catch(cause){if(cause instanceof DOMException&&cause.name==='AbortError')return;setError(cause instanceof Error?cause.message:t('sharing.error.handoff'));}};
 const revoke=async()=>{const r=runtimeRef.current;if(!r||!grant)return;const revoked=revokePartnerGrant(grant,new Date().toISOString());await r.grants.save(revoked);setGrant(revoked);setSharePackage(null);setStatus(t('sharing.status.revoked'));};
 return <section className="account-free-core" data-testid="sharing-workspace" aria-busy={!ready}><div className="account-free-core__status"><StatusChip tone={error?'danger':ready?'success':'info'}>{status}</StatusChip><span className="workspace-note">{t('sharing.status')}</span></div>{error?<p className="core-error" role="alert">{error}</p>:null}
 {ready?<div className="workspace-grid"><Card eyebrow={t('sharing.eyebrow')} title={t('sharing.title')}><fieldset><legend>{t('sharing.legend')}</legend>{PARTNER_SHARE_CATEGORIES.map(c=><label key={c} className="core-check-row"><input type="checkbox" checked={categories.includes(c)} onChange={e=>toggle(c,e.target.checked)}/><span>{label(c)}</span></label>)}</fieldset>
 {categories.includes('cyclePhase')?<label><span>{t('sharing.cyclePhase')}</span><input aria-label={t('sharing.cyclePhase')} value={cyclePhase} onChange={e=>{setCyclePhase(e.target.value);invalidate();}}/></label>:null}
 {categories.includes('selectedReminder')?<label><span>{t('sharing.reminder')}</span><input aria-label={t('sharing.reminder')} value={selectedReminder} onChange={e=>{setSelectedReminder(e.target.value);invalidate();}}/></label>:null}
 {categories.includes('selectedWellness')?<label><span>{t('sharing.wellness')}</span><input aria-label={t('sharing.wellness')} value={selectedWellness} onChange={e=>{setSelectedWellness(e.target.value);invalidate();}}/></label>:null}
 <p className="workspace-note">{t('sharing.exclusion')}</p><Button onClick={()=>{void prepare();}}>{t('sharing.preview')}</Button></Card>
 <Card eyebrow={t('sharing.reviewEyebrow')} title={t('sharing.reviewTitle')}>{!sharePackage?<p>{t('sharing.empty')}</p>:<><pre data-testid="partner-share-preview" style={{whiteSpace:'pre-wrap'}}>{sharePackage.summary}</pre><div aria-label={t('sharing.qrAria')} data-testid="partner-share-qr"><QRCodeSVG value={sharePackage.qrPayload} size={196} level="M" marginSize={4}/></div><p className="workspace-note">{t('sharing.qrNote')}</p><div className="core-actions"><Button onClick={()=>{void share();}}>{t('sharing.share')}</Button><Button variant="quiet" onClick={()=>{void revoke();}}>{t('sharing.revoke')}</Button></div><p className="workspace-note">{t('sharing.revokeNote')}</p></>}</Card></div>:null}</section>;
}
